// ibet settlement keeper
//
// Runs every minute from pg_cron. Reads every matched bet off the chain, walks
// the 1-minute candles of the coin's main pool, and settles the moment a candle
// touches the target. If the deadline passes with the whole window checked and
// untouched, the taker wins.
//
// Two RPCs, on purpose: the escrow lives on devnet, but the coins people bet on
// are real mainnet tokens, so supply is read from mainnet.
//
// The signing key is generated by this function and kept in Supabase Vault. It
// is never in the repo. `?action=init-key` mints it once and returns only the
// public key.

import { createClient } from "npm:@supabase/supabase-js@2.57.4";
import {
  Connection,
  Keypair,
  PublicKey,
  Transaction,
  TransactionInstruction,
} from "npm:@solana/web3.js@1.98.4";

const PROGRAM_ID = new PublicKey("51Qu3DKZZ9bHJKiNyXhKcTp7PqJNW1YqVcx7Cqm6Vyv");
const ESCROW_RPC = "https://api.devnet.solana.com";
const DATA_RPC = "https://api.mainnet-beta.solana.com";
const CLUSTER = "devnet";

const BET_SIZE = 221;
const CONFIG_SIZE = 132;
const BET_DISC = [147, 23, 35, 59, 15, 75, 155, 32];
const IX_SETTLE = [115, 55, 234, 177, 227, 4, 10, 67];

const DIRECTION_HIGHER = 0;
const OUTCOME_CREATOR_WINS = 0;
const OUTCOME_TAKER_WINS = 1;

/// One page of GeckoTerminal candles, and how many pages one run may walk.
const CANDLE_PAGE = 1000;
const MAX_PAGES = 5;
const SOURCE = "geckoterminal:ohlcv/minute";

const escrow = new Connection(ESCROW_RPC, "confirmed");
const mainnet = new Connection(DATA_RPC, "confirmed");
const db = createClient(
  Deno.env.get("SUPABASE_URL")!,
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
);

// ── borsh ────────────────────────────────────────────────────────────────────

class Rd {
  a: Uint8Array;
  v: DataView;
  o = 0;
  constructor(a: Uint8Array) {
    this.a = a;
    this.v = new DataView(a.buffer, a.byteOffset, a.byteLength);
  }
  u8() { return this.a[this.o++]; }
  u16() { const x = this.v.getUint16(this.o, true); this.o += 2; return x; }
  u64() { const x = this.v.getBigUint64(this.o, true); this.o += 8; return Number(x); }
  i64() { const x = this.v.getBigInt64(this.o, true); this.o += 8; return Number(x); }
  bool() { return this.u8() === 1; }
  key() { const k = new PublicKey(this.a.subarray(this.o, this.o + 32)); this.o += 32; return k; }
  optKey() { return this.u8() ? this.key() : null; }
  skip(n: number) { this.o += n; return this; }
}

function w64(n: number | bigint): number[] {
  let v = BigInt(n);
  const out: number[] = [];
  for (let i = 0; i < 8; i++) { out.push(Number(v & 0xffn)); v >>= 8n; }
  return out;
}

const STATUS = ["open", "matched", "settled", "cancelled", "refunded"] as const;

type Bet = {
  address: string;
  creator: PublicKey;
  taker: PublicKey | null;
  tokenMint: PublicKey;
  direction: number;
  targetMcapUsd: number;
  startMcapUsd: number;
  stakeLamports: number;
  durationSecs: number;
  createdAt: number;
  takenAt: number;
  expiresAt: number;
  status: string;
  winner: PublicKey | null;
  observedMcapUsd: number;
  observedAt: number;
  betId: number;
};

function decodeBet(address: string, data: Uint8Array): Bet | null {
  if (data.length !== BET_SIZE) return null;
  for (let i = 0; i < 8; i++) if (data[i] !== BET_DISC[i]) return null;
  const r = new Rd(data).skip(8);
  return {
    address,
    creator: r.key(),
    taker: r.optKey(),
    tokenMint: r.key(),
    direction: r.u8(),
    targetMcapUsd: r.u64(),
    startMcapUsd: r.u64(),
    stakeLamports: r.u64(),
    durationSecs: r.i64(),
    createdAt: r.i64(),
    takenAt: r.i64(),
    expiresAt: r.i64(),
    status: STATUS[r.u8()] ?? "open",
    winner: r.optKey(),
    observedMcapUsd: r.u64(),
    observedAt: r.i64(),
    betId: r.u64(),
  };
}

const configPda = () =>
  PublicKey.findProgramAddressSync([new TextEncoder().encode("config")], PROGRAM_ID)[0];

async function readConfig() {
  const info = await escrow.getAccountInfo(configPda());
  if (!info || info.data.length !== CONFIG_SIZE) throw new Error("config account missing");
  const r = new Rd(new Uint8Array(info.data)).skip(8);
  return {
    admin: r.key(),
    resolver: r.key(),
    feeWallet: r.key(),
    feeBps: r.u16(),
    minStake: r.u64(),
    maxStake: r.u64(),
    graceSecs: r.i64(),
    paused: r.bool(),
  };
}

// ── market data ──────────────────────────────────────────────────────────────

const supplyCache = new Map<string, number>();

/// Total supply, in whole tokens, read from mainnet where the coin actually
/// lives. Market cap is price × this — the same definition the UI shows.
async function totalSupply(mint: PublicKey): Promise<number | null> {
  const key = mint.toBase58();
  if (supplyCache.has(key)) return supplyCache.get(key)!;
  try {
    const res = await mainnet.getTokenSupply(mint);
    const amount = Number(res.value.uiAmountString ?? res.value.uiAmount ?? 0);
    if (!Number.isFinite(amount) || amount <= 0) return null;
    supplyCache.set(key, amount);
    return amount;
  } catch {
    return null;
  }
}

/// The deepest pool for a token, which is the one whose candles we trust.
async function mainPool(mint: PublicKey): Promise<string | null> {
  try {
    const res = await fetch(`https://api.dexscreener.com/latest/dex/tokens/${mint.toBase58()}`);
    if (!res.ok) return null;
    const json = await res.json();
    const pairs = (json.pairs ?? []).filter((p: any) => p.chainId === "solana");
    if (!pairs.length) return null;
    pairs.sort((a: any, b: any) => (b.liquidity?.usd ?? 0) - (a.liquidity?.usd ?? 0));
    return pairs[0].pairAddress ?? null;
  } catch {
    return null;
  }
}

type Candle = { t: number; high: number; low: number; close: number };

/// Minute candles for a pool, newest first from GeckoTerminal, walked backwards
/// until we reach `fromTs` or run out of pages.
async function candlesSince(pool: string, fromTs: number): Promise<Candle[]> {
  const out: Candle[] = [];
  let before: number | null = null;
  for (let page = 0; page < MAX_PAGES; page++) {
    const url = new URL(
      `https://api.geckoterminal.com/api/v2/networks/solana/pools/${pool}/ohlcv/minute`,
    );
    url.searchParams.set("aggregate", "1");
    url.searchParams.set("limit", String(CANDLE_PAGE));
    url.searchParams.set("currency", "usd");
    url.searchParams.set("token", "base");
    if (before !== null) url.searchParams.set("before_timestamp", String(before));

    const res = await fetch(url, { headers: { accept: "application/json" } });
    if (!res.ok) break;
    const json = await res.json();
    const list: number[][] = json?.data?.attributes?.ohlcv_list ?? [];
    if (!list.length) break;

    for (const [t, , h, l, c] of list) {
      if (t >= fromTs) out.push({ t, high: h, low: l, close: c });
    }
    const oldest = list[list.length - 1][0];
    if (oldest <= fromTs) break;
    before = oldest;
  }
  out.sort((a, b) => a.t - b.t);
  return out;
}

// ── settling ─────────────────────────────────────────────────────────────────

function ixSettle(
  keeper: PublicKey,
  bet: Bet,
  feeWallet: PublicKey,
  outcome: number,
  observedMcapUsd: number,
  observedAt: number,
) {
  const data = new Uint8Array([
    ...IX_SETTLE,
    outcome,
    ...w64(Math.round(observedMcapUsd)),
    ...w64(Math.round(observedAt)),
  ]);
  return new TransactionInstruction({
    programId: PROGRAM_ID,
    data,
    keys: [
      { pubkey: keeper, isSigner: true, isWritable: true },
      { pubkey: configPda(), isSigner: false, isWritable: false },
      { pubkey: new PublicKey(bet.address), isSigner: false, isWritable: true },
      { pubkey: bet.creator, isSigner: false, isWritable: true },
      { pubkey: bet.taker!, isSigner: false, isWritable: true },
      { pubkey: feeWallet, isSigner: false, isWritable: true },
    ],
  });
}

async function send(keeper: Keypair, ix: TransactionInstruction): Promise<string> {
  const tx = new Transaction().add(ix);
  tx.feePayer = keeper.publicKey;
  tx.recentBlockhash = (await escrow.getLatestBlockhash("confirmed")).blockhash;
  tx.sign(keeper);
  const sig = await escrow.sendRawTransaction(tx.serialize());
  await escrow.confirmTransaction(sig, "confirmed");
  return sig;
}

// ── the run ──────────────────────────────────────────────────────────────────

async function loadKeeper(): Promise<Keypair> {
  const { data, error } = await db.rpc("keeper_key_get");
  if (error) throw new Error(`vault read failed: ${error.message}`);
  if (!data) throw new Error("no keeper key in the vault — call ?action=init-key first");
  return Keypair.fromSecretKey(Uint8Array.from(JSON.parse(data as string)));
}

async function initKey() {
  const existing = await db.rpc("keeper_key_get");
  if (existing.data) {
    const kp = Keypair.fromSecretKey(Uint8Array.from(JSON.parse(existing.data as string)));
    return { created: false, keeper: kp.publicKey.toBase58() };
  }
  const kp = Keypair.generate();
  const { error } = await db.rpc("keeper_key_set", {
    p_key: JSON.stringify(Array.from(kp.secretKey)),
  });
  if (error) throw new Error(`vault write failed: ${error.message}`);
  // Only the public half ever leaves this function.
  return { created: true, keeper: kp.publicKey.toBase58() };
}

async function mirror(bet: Bet, extra: Record<string, unknown> = {}) {
  const iso = (s: number) => (s > 0 ? new Date(s * 1000).toISOString() : null);
  await db.from("chain_bets").upsert({
    bet_address: bet.address,
    bet_id: bet.betId,
    creator: bet.creator.toBase58(),
    taker: bet.taker?.toBase58() ?? null,
    token_mint: bet.tokenMint.toBase58(),
    direction: bet.direction,
    target_mcap_usd: bet.targetMcapUsd,
    start_mcap_usd: bet.startMcapUsd || null,
    stake_lamports: bet.stakeLamports,
    duration_secs: bet.durationSecs,
    created_at: iso(bet.createdAt),
    taken_at: iso(bet.takenAt),
    expires_at: iso(bet.expiresAt),
    status: bet.status,
    winner: bet.winner?.toBase58() ?? null,
    updated_at: new Date().toISOString(),
    ...extra,
  }, { onConflict: "bet_address" });
}

async function run() {
  const started = Date.now();
  const config = await readConfig();
  const keeper = await loadKeeper();
  if (!keeper.publicKey.equals(config.resolver)) {
    return {
      ok: false,
      error: "the vault key is not the configured resolver",
      keeper: keeper.publicKey.toBase58(),
      resolver: config.resolver.toBase58(),
    };
  }

  const accounts = await escrow.getProgramAccounts(PROGRAM_ID, {
    commitment: "confirmed",
    filters: [{ dataSize: BET_SIZE }],
  });

  const bets: Bet[] = [];
  for (const { pubkey, account } of accounts) {
    const b = decodeBet(pubkey.toBase58(), new Uint8Array(account.data));
    if (b) bets.push(b);
  }

  // Everything on chain gets mirrored, so the site keeps a history after the
  // accounts are closed.
  for (const b of bets) await mirror(b);

  const matched = bets.filter((b) => b.status === "matched" && b.taker);
  const now = Math.floor(Date.now() / 1000);
  const results: unknown[] = [];

  for (const bet of matched) {
    try {
      const supply = await totalSupply(bet.tokenMint);
      if (!supply) { results.push({ bet: bet.address, skipped: "no supply on mainnet" }); continue; }

      const { data: row } = await db
        .from("chain_bets").select("checked_through, pool_address")
        .eq("bet_address", bet.address).maybeSingle();

      const pool = row?.pool_address ?? await mainPool(bet.tokenMint);
      if (!pool) { results.push({ bet: bet.address, skipped: "no pool found" }); continue; }

      // Re-check the last minute we saw, in case that candle was still forming.
      const from = row?.checked_through
        ? Math.floor(new Date(row.checked_through).getTime() / 1000) - 60
        : bet.takenAt;
      const candles = await candlesSince(pool, Math.max(from, bet.takenAt));
      if (!candles.length) { results.push({ bet: bet.address, skipped: "no candles" }); continue; }

      const inWindow = candles.filter((c) => c.t >= bet.takenAt && c.t <= bet.expiresAt);
      const higher = bet.direction === DIRECTION_HIGHER;

      // A touch is the candle's high for a Higher bet, its low for a Lower one.
      let hit: Candle | null = null;
      let hitMcap = 0;
      for (const c of inWindow) {
        const mcap = (higher ? c.high : c.low) * supply;
        if (higher ? mcap >= bet.targetMcapUsd : mcap <= bet.targetMcapUsd) {
          hit = c;
          hitMcap = mcap;
          break;
        }
      }

      const newestChecked = candles[candles.length - 1].t;
      const coveredThroughEnd = newestChecked >= bet.expiresAt;

      if (hit) {
        const sig = await send(
          keeper,
          ixSettle(keeper.publicKey, bet, config.feeWallet, OUTCOME_CREATOR_WINS, hitMcap, hit.t),
        );
        await db.from("settlements").upsert({
          bet_address: bet.address,
          outcome: "creator_wins",
          observed_mcap_usd: Math.round(hitMcap),
          observed_at: new Date(hit.t * 1000).toISOString(),
          candle_high_usd: hit.high,
          candle_low_usd: hit.low,
          source: SOURCE,
          pool_address: pool,
          tx_signature: sig,
        }, { onConflict: "bet_address" });
        await mirror({ ...bet, status: "settled", winner: bet.creator }, {
          observed_mcap_usd: Math.round(hitMcap),
          observed_at: new Date(hit.t * 1000).toISOString(),
          pool_address: pool,
          checked_through: new Date(newestChecked * 1000).toISOString(),
        });
        results.push({ bet: bet.address, settled: "creator_wins", mcap: Math.round(hitMcap), sig });
        continue;
      }

      if (now >= bet.expiresAt && coveredThroughEnd) {
        const last = inWindow[inWindow.length - 1] ?? candles[candles.length - 1];
        const lastMcap = last.close * supply;
        const sig = await send(
          keeper,
          ixSettle(
            keeper.publicKey, bet, config.feeWallet,
            OUTCOME_TAKER_WINS, lastMcap, bet.expiresAt,
          ),
        );
        await db.from("settlements").upsert({
          bet_address: bet.address,
          outcome: "taker_wins",
          observed_mcap_usd: Math.round(lastMcap),
          observed_at: new Date(bet.expiresAt * 1000).toISOString(),
          candle_high_usd: last.high,
          candle_low_usd: last.low,
          source: SOURCE,
          pool_address: pool,
          tx_signature: sig,
        }, { onConflict: "bet_address" });
        await mirror({ ...bet, status: "settled", winner: bet.taker }, {
          observed_mcap_usd: Math.round(lastMcap),
          observed_at: new Date(bet.expiresAt * 1000).toISOString(),
          pool_address: pool,
          checked_through: new Date(newestChecked * 1000).toISOString(),
        });
        results.push({ bet: bet.address, settled: "taker_wins", mcap: Math.round(lastMcap), sig });
        continue;
      }

      // Nothing to do yet — remember how far we got so the next run is cheap.
      await mirror(bet, {
        pool_address: pool,
        checked_through: new Date(newestChecked * 1000).toISOString(),
      });
      results.push({ bet: bet.address, watching: true, checked_through: newestChecked });
    } catch (e) {
      // A bad source or a failed send must never stop the other bets, and the
      // 48h refund remains the safety net.
      await mirror(bet, { keeper_note: String(e).slice(0, 300) });
      results.push({ bet: bet.address, error: String(e).slice(0, 300) });
    }
  }

  return { ok: true, bets: bets.length, matched: matched.length, ms: Date.now() - started, results };
}

/// Constant-time compare, so the token can't be guessed a character at a time.
function sameToken(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

// JWT verification is off because the caller is pg_cron, not a signed-in user.
// Instead the function checks a shared token that Postgres minted into the
// vault and hands over on every request.
Deno.serve(async (req: Request) => {
  const json = (body: unknown, status = 200) =>
    new Response(JSON.stringify(body, null, 2), {
      status,
      headers: { "content-type": "application/json" },
    });
  try {
    const { data: expected } = await db.rpc("keeper_token_get");
    const given = req.headers.get("x-keeper-token") ?? "";
    if (!expected || !sameToken(given, expected as string)) {
      return json({ ok: false, error: "unauthorized" }, 401);
    }
    const action = new URL(req.url).searchParams.get("action");
    if (action === "init-key") return json(await initKey());
    return json(await run());
  } catch (e) {
    return json({ ok: false, error: String(e) }, 500);
  }
});
