// ibet settlement keeper
//
// Runs every minute from pg_cron. Reads every matched bet off the chain, walks
// the 1-minute candles of the coin's main pool, and settles the moment a candle
// touches the target. If the deadline passes with the whole window checked and
// untouched, the taker wins.
//
// Two RPCs, on purpose: the escrow lives on devnet, but the coins people bet on
// are real mainnet tokens, so supply is read from mainnet.
//
// The signing key is generated by this function and kept in Supabase Vault. It
// is never in the repo. `?action=init-key` mints it once and returns only the
// public key.

import { createClient } from "npm:@supabase/supabase-js@2.57.4";
import {
  Connection,
  Keypair,
  PublicKey,
  Transaction,
  TransactionInstruction,
} from "npm:@solana/web3.js@1.98.4";

const PROGRAM_ID = new PublicKey("51Qu3DKZZ9bHJKiNyXhKcTp7PqJNW1YqVcx7Cqm6Vyv");
const ESCROW_RPC = "https://api.devnet.solana.com";
const DATA_RPC = "https://api.mainnet-beta.solana.com";

const BET_SIZE = 221;
// Phase 3 appended the exposure counter. Devnet still runs the phase-2
// program, whose config is 16 bytes shorter, so both are readable.
const CONFIG_SIZE_V1 = 132;
const CONFIG_SIZE_V2 = 148;
const BET_DISC = [147, 23, 35, 59, 15, 75, 155, 32];
const IX_SETTLE = [115, 55, 234, 177, 227, 4, 10, 67];

const DIRECTION_HIGHER = 0;
const OUTCOME_CREATOR_WINS = 0;
const OUTCOME_TAKER_WINS = 1;

/// One page of GeckoTerminal candles, and how many pages one run may walk.
const CANDLE_PAGE = 1000;
const MAX_PAGES = 5;
const SOURCE = "geckoterminal:ohlcv/minute";

// ── the sanity check ─────────────────────────────────────────────────────────
// GeckoTerminal decides every outcome; a second provider only guards against
// its data being broken. It never changes who wins.
//
// It is called only when a settlement is actually about to happen. Calling it
// once per run is not affordable: the keeper wakes every minute, which is
// ~43,200 runs a month, already past the free allowance with a single live bet
// before any other cost. At settlement time it is a handful of calls a day.
const SECOND_PROVIDER = "birdeye";
const SANITY_TOLERANCE = 0.05;      // 5%
const SKEW_SECS = 60;               // ±1 minute, for clock skew between sources
/// Hard ceiling on calls per calendar month, well inside the free allowance.
/// Past it the keeper stops asking and settles on the deciding source alone
/// rather than stalling — and says so, loudly.
const SECOND_BUDGET = 1500;

const escrow = new Connection(ESCROW_RPC, "confirmed");
const mainnet = new Connection(DATA_RPC, "confirmed");
const db = createClient(
  Deno.env.get("SUPABASE_URL")!,
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
);

// ── borsh ────────────────────────────────────────────────────────────────────

class Rd {
  a: Uint8Array;
  v: DataView;
  o = 0;
  constructor(a: Uint8Array) {
    this.a = a;
    this.v = new DataView(a.buffer, a.byteOffset, a.byteLength);
  }
  u8() { return this.a[this.o++]; }
  u16() { const x = this.v.getUint16(this.o, true); this.o += 2; return x; }
  u64() { const x = this.v.getBigUint64(this.o, true); this.o += 8; return Number(x); }
  i64() { const x = this.v.getBigInt64(this.o, true); this.o += 8; return Number(x); }
  bool() { return this.u8() === 1; }
  key() { const k = new PublicKey(this.a.subarray(this.o, this.o + 32)); this.o += 32; return k; }
  optKey() { return this.u8() ? this.key() : null; }
  skip(n: number) { this.o += n; return this; }
}

function w64(n: number | bigint): number[] {
  let v = BigInt(n);
  const out: number[] = [];
  for (let i = 0; i < 8; i++) { out.push(Number(v & 0xffn)); v >>= 8n; }
  return out;
}

const STATUS = ["open", "matched", "settled", "cancelled", "refunded"] as const;

type Bet = {
  address: string;
  creator: PublicKey;
  taker: PublicKey | null;
  tokenMint: PublicKey;
  direction: number;
  targetMcapUsd: number;
  startMcapUsd: number;
  stakeLamports: number;
  durationSecs: number;
  createdAt: number;
  takenAt: number;
  expiresAt: number;
  status: string;
  winner: PublicKey | null;
  observedMcapUsd: number;
  observedAt: number;
  betId: number;
};

function decodeBet(address: string, data: Uint8Array): Bet | null {
  if (data.length !== BET_SIZE) return null;
  for (let i = 0; i < 8; i++) if (data[i] !== BET_DISC[i]) return null;
  const r = new Rd(data).skip(8);
  return {
    address,
    creator: r.key(),
    taker: r.optKey(),
    tokenMint: r.key(),
    direction: r.u8(),
    targetMcapUsd: r.u64(),
    startMcapUsd: r.u64(),
    stakeLamports: r.u64(),
    durationSecs: r.i64(),
    createdAt: r.i64(),
    takenAt: r.i64(),
    expiresAt: r.i64(),
    status: STATUS[r.u8()] ?? "open",
    winner: r.optKey(),
    observedMcapUsd: r.u64(),
    observedAt: r.i64(),
    betId: r.u64(),
  };
}

const configPda = () =>
  PublicKey.findProgramAddressSync([new TextEncoder().encode("config")], PROGRAM_ID)[0];

async function readConfig() {
  const info = await escrow.getAccountInfo(configPda());
  if (!info) throw new Error("config account missing");
  const len = info.data.length;
  if (len !== CONFIG_SIZE_V1 && len !== CONFIG_SIZE_V2) {
    throw new Error(`unexpected config size ${len}`);
  }
  const r = new Rd(new Uint8Array(info.data)).skip(8);
  const config = {
    admin: r.key(),
    resolver: r.key(),
    feeWallet: r.key(),
    feeBps: r.u16(),
    minStake: r.u64(),
    maxStake: r.u64(),
    graceSecs: r.i64(),
    paused: r.bool(),
    openExposure: 0,
    maxOpenExposure: 0,
  };
  r.u8(); // bump
  if (len === CONFIG_SIZE_V2) {
    config.openExposure = r.u64();
    config.maxOpenExposure = r.u64();
  }
  return config;
}

// ── market data ──────────────────────────────────────────────────────────────

const supplyCache = new Map<string, number>();

/// Total supply, in whole tokens, read from mainnet where the coin actually
/// lives. Market cap is price × this — the same definition the UI shows.
async function totalSupply(mint: PublicKey): Promise<number | null> {
  const key = mint.toBase58();
  if (supplyCache.has(key)) return supplyCache.get(key)!;
  try {
    const res = await mainnet.getTokenSupply(mint);
    const amount = Number(res.value.uiAmountString ?? res.value.uiAmount ?? 0);
    if (!Number.isFinite(amount) || amount <= 0) return null;
    supplyCache.set(key, amount);
    return amount;
  } catch {
    return null;
  }
}

/// Which pool a bet is judged on.
///
/// Depth is what makes a price hard to push around, so the deepest pool is the
/// one to trust — but only among the pools that are actually trading. A deep
/// pool that has gone quiet produces no candles at all, and a bet with no
/// candles cannot be settled either way: it just sits until the 48-hour
/// refund. That is not a hypothetical. PAID's deepest pool sat for eleven
/// minutes with zero trades while two shallower ones traded throughout.
///
/// So: prefer pools trading in the last five minutes, then the last hour, and
/// within each group take the deepest. Falling back to raw depth only when
/// nothing at all is trading, where a refund is the honest outcome anyway.
///
/// index.html picks the pool the same way, so the chart shows the pool the bet
/// resolves on.
export function pickPool(pairs: any[]): string | null {
  const solana = (pairs ?? []).filter((p: any) => p?.chainId === "solana" && p?.pairAddress);
  if (!solana.length) return null;
  const liq = (p: any) => p.liquidity?.usd ?? 0;
  const trades = (p: any, w: "m5" | "h1") =>
    (p.txns?.[w]?.buys ?? 0) + (p.txns?.[w]?.sells ?? 0);

  for (const window of ["m5", "h1"] as const) {
    const active = solana.filter((p: any) => trades(p, window) > 0);
    if (active.length) {
      active.sort((a: any, b: any) => liq(b) - liq(a));
      return active[0].pairAddress;
    }
  }
  solana.sort((a: any, b: any) => liq(b) - liq(a));
  return solana[0].pairAddress;
}

async function mainPool(mint: PublicKey): Promise<string | null> {
  try {
    const res = await fetch(`https://api.dexscreener.com/latest/dex/tokens/${mint.toBase58()}`);
    if (!res.ok) return null;
    return pickPool((await res.json()).pairs ?? []);
  } catch {
    return null;
  }
}

type Candle = { t: number; high: number; low: number; close: number };

/// Minute candles for a pool, newest first from GeckoTerminal, walked backwards
/// until we reach `fromTs` or run out of pages.
async function candlesSince(pool: string, fromTs: number): Promise<Candle[]> {
  const out: Candle[] = [];
  let before: number | null = null;
  for (let page = 0; page < MAX_PAGES; page++) {
    const url = new URL(
      `https://api.geckoterminal.com/api/v2/networks/solana/pools/${pool}/ohlcv/minute`,
    );
    url.searchParams.set("aggregate", "1");
    url.searchParams.set("limit", String(CANDLE_PAGE));
    url.searchParams.set("currency", "usd");
    url.searchParams.set("token", "base");
    if (before !== null) url.searchParams.set("before_timestamp", String(before));

    const res = await fetch(url, { headers: { accept: "application/json" } });
    if (!res.ok) break;
    const json = await res.json();
    const list: number[][] = json?.data?.attributes?.ohlcv_list ?? [];
    if (!list.length) break;

    for (const [t, , h, l, c] of list) {
      if (t >= fromTs) out.push({ t, high: h, low: l, close: c });
    }
    const oldest = list[list.length - 1][0];
    if (oldest <= fromTs) break;
    before = oldest;
  }
  out.sort((a, b) => a.t - b.t);
  return out;
}

// ── alerts ───────────────────────────────────────────────────────────────────

/// Recorded whether or not a webhook is configured, so nothing is lost while
/// one is still being set up.
async function alert(
  level: "info" | "warn" | "error",
  kind: string,
  message: string,
  detail: Record<string, unknown> = {},
) {
  let delivered = false;
  try {
    const { data: url } = await db.rpc("alert_webhook_get");
    if (url) {
      const res = await fetch(url as string, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ content: `[${level}] ${message}` }),
        signal: AbortSignal.timeout(5000),
      });
      delivered = res.ok;
    }
  } catch { /* a failed alert must never stop a settlement */ }
  try {
    await db.from("alerts").insert({ level, kind, message, detail, delivered });
  } catch { /* same */ }
}

// ── second source ────────────────────────────────────────────────────────────

const monthKey = () => new Date().toISOString().slice(0, 7);

type SecondCheck = {
  sanity: "ok" | "deviation" | "unavailable" | "skipped";
  value: number | null;
  deviation: number | null;
};

/// One call per deciding candle, memoised for the run.
const secondCache = new Map<string, number | null>();

async function birdeyeExtreme(
  mint: string,
  minuteTs: number,
  wantHigh: boolean,
): Promise<number | null> {
  const key = `${mint}|${minuteTs}|${wantHigh}`;
  if (secondCache.has(key)) return secondCache.get(key)!;

  const { data: apiKey } = await db.rpc("birdeye_key_get");
  if (!apiKey) return null;

  const url = new URL("https://public-api.birdeye.so/defi/ohlcv");
  url.searchParams.set("address", mint);
  url.searchParams.set("type", "1m");
  url.searchParams.set("time_from", String(minuteTs - SKEW_SECS));
  url.searchParams.set("time_to", String(minuteTs + SKEW_SECS));

  let value: number | null = null;
  try {
    const res = await fetch(url, {
      headers: { "X-API-KEY": apiKey as string, "x-chain": "solana", accept: "application/json" },
      signal: AbortSignal.timeout(8000),
    });
    await db.rpc("provider_usage_bump", { p_provider: SECOND_PROVIDER, p_month: monthKey() });
    if (res.ok) {
      const items = (await res.json())?.data?.items ?? [];
      const picked = items
        .map((i: any) => Number(wantHigh ? i.h : i.l))
        .filter((n: number) => Number.isFinite(n) && n > 0);
      if (picked.length) value = wantHigh ? Math.max(...picked) : Math.min(...picked);
    }
  } catch { /* treated as unavailable below */ }

  secondCache.set(key, value);
  return value;
}

/// Compares the deciding market cap with the second source over the same
/// minute. Within tolerance settles; a real disagreement does not.
async function sanityCheck(
  mint: string,
  minuteTs: number,
  wantHigh: boolean,
  decidingMcap: number,
  supply: number,
): Promise<SecondCheck> {
  const { data: used } = await db
    .from("provider_usage").select("calls")
    .eq("provider", SECOND_PROVIDER).eq("month", monthKey()).maybeSingle();
  if ((used?.calls ?? 0) >= SECOND_BUDGET) {
    await alert("warn", "second-source-budget",
      `${SECOND_PROVIDER} monthly budget of ${SECOND_BUDGET} calls is spent; settling on ${SOURCE} alone`);
    return { sanity: "skipped", value: null, deviation: null };
  }

  const price = await birdeyeExtreme(mint, minuteTs, wantHigh);
  if (price === null) return { sanity: "unavailable", value: null, deviation: null };

  const second = price * supply;
  const deviation = decidingMcap > 0 ? Math.abs(decidingMcap - second) / decidingMcap : 0;
  return {
    sanity: deviation <= SANITY_TOLERANCE ? "ok" : "deviation",
    value: second,
    deviation,
  };
}

// ── settling ─────────────────────────────────────────────────────────────────

function ixSettle(
  keeper: PublicKey,
  bet: Bet,
  feeWallet: PublicKey,
  outcome: number,
  observedMcapUsd: number,
  observedAt: number,
) {
  const data = new Uint8Array([
    ...IX_SETTLE,
    outcome,
    ...w64(Math.round(observedMcapUsd)),
    ...w64(Math.round(observedAt)),
  ]);
  return new TransactionInstruction({
    programId: PROGRAM_ID,
    // web3.js types this as a Node Buffer, but a Uint8Array is what actually
    // gets serialised and what the Deno runtime hands us — this is how the
    // keeper has been settling bets since phase 2. Taking the type from the
    // library itself keeps `deno check` useful as a gate instead of
    // permanently red on a types-only mismatch.
    data: data as unknown as ConstructorParameters<
      typeof TransactionInstruction
    >[0]["data"],
    keys: [
      { pubkey: keeper, isSigner: true, isWritable: true },
      { pubkey: configPda(), isSigner: false, isWritable: false },
      { pubkey: new PublicKey(bet.address), isSigner: false, isWritable: true },
      { pubkey: bet.creator, isSigner: false, isWritable: true },
      { pubkey: bet.taker!, isSigner: false, isWritable: true },
      { pubkey: feeWallet, isSigner: false, isWritable: true },
    ],
  });
}

async function send(keeper: Keypair, ix: TransactionInstruction): Promise<string> {
  const tx = new Transaction().add(ix);
  tx.feePayer = keeper.publicKey;
  tx.recentBlockhash = (await escrow.getLatestBlockhash("confirmed")).blockhash;
  tx.sign(keeper);
  const sig = await escrow.sendRawTransaction(tx.serialize());
  await escrow.confirmTransaction(sig, "confirmed");
  return sig;
}

// ── the run ──────────────────────────────────────────────────────────────────

async function loadKeeper(): Promise<Keypair> {
  const { data, error } = await db.rpc("keeper_key_get");
  if (error) throw new Error(`vault read failed: ${error.message}`);
  if (!data) throw new Error("no keeper key in the vault — call ?action=init-key first");
  return Keypair.fromSecretKey(Uint8Array.from(JSON.parse(data as string)));
}

async function initKey() {
  const existing = await db.rpc("keeper_key_get");
  if (existing.data) {
    const kp = Keypair.fromSecretKey(Uint8Array.from(JSON.parse(existing.data as string)));
    return { created: false, keeper: kp.publicKey.toBase58() };
  }
  const kp = Keypair.generate();
  const { error } = await db.rpc("keeper_key_set", {
    p_key: JSON.stringify(Array.from(kp.secretKey)),
  });
  if (error) throw new Error(`vault write failed: ${error.message}`);
  // Only the public half ever leaves this function.
  return { created: true, keeper: kp.publicKey.toBase58() };
}

async function mirror(bet: Bet, extra: Record<string, unknown> = {}) {
  const iso = (s: number) => (s > 0 ? new Date(s * 1000).toISOString() : null);
  await db.from("chain_bets").upsert({
    bet_address: bet.address,
    bet_id: bet.betId,
    creator: bet.creator.toBase58(),
    taker: bet.taker?.toBase58() ?? null,
    token_mint: bet.tokenMint.toBase58(),
    direction: bet.direction,
    target_mcap_usd: bet.targetMcapUsd,
    start_mcap_usd: bet.startMcapUsd || null,
    stake_lamports: bet.stakeLamports,
    duration_secs: bet.durationSecs,
    created_at: iso(bet.createdAt),
    taken_at: iso(bet.takenAt),
    expires_at: iso(bet.expiresAt),
    status: bet.status,
    winner: bet.winner?.toBase58() ?? null,
    updated_at: new Date().toISOString(),
    ...extra,
  }, { onConflict: "bet_address" });
}

async function run() {
  const started = Date.now();
  const config = await readConfig();
  const keeper = await loadKeeper();
  if (!keeper.publicKey.equals(config.resolver)) {
    return {
      ok: false,
      error: "the vault key is not the configured resolver",
      keeper: keeper.publicKey.toBase58(),
      resolver: config.resolver.toBase58(),
    };
  }

  const accounts = await escrow.getProgramAccounts(PROGRAM_ID, {
    commitment: "confirmed",
    filters: [{ dataSize: BET_SIZE }],
  });

  const bets: Bet[] = [];
  for (const { pubkey, account } of accounts) {
    const b = decodeBet(pubkey.toBase58(), new Uint8Array(account.data));
    if (b) bets.push(b);
  }

  // Everything on chain gets mirrored, so the site keeps a history after the
  // accounts are closed.
  for (const b of bets) await mirror(b);

  const matched = bets.filter((b) => b.status === "matched" && b.taker);
  const now = Math.floor(Date.now() / 1000);
  const results: unknown[] = [];

  for (const bet of matched) {
    try {
      const supply = await totalSupply(bet.tokenMint);
      if (!supply) { results.push({ bet: bet.address, skipped: "no supply on mainnet" }); continue; }

      const { data: row } = await db
        .from("chain_bets").select("checked_through, pool_address")
        .eq("bet_address", bet.address).maybeSingle();

      const pool = row?.pool_address ?? await mainPool(bet.tokenMint);
      if (!pool) { results.push({ bet: bet.address, skipped: "no pool found" }); continue; }

      // Re-check the last minute we saw, in case that candle was still forming.
      const from = row?.checked_through
        ? Math.floor(new Date(row.checked_through).getTime() / 1000) - 60
        : bet.takenAt;
      const candles = await candlesSince(pool, Math.max(from, bet.takenAt));
      if (!candles.length) { results.push({ bet: bet.address, skipped: "no candles" }); continue; }

      const inWindow = candles.filter((c) => c.t >= bet.takenAt && c.t <= bet.expiresAt);
      const higher = bet.direction === DIRECTION_HIGHER;

      // A touch is the candle's high for a Higher bet, its low for a Lower one.
      let hit: Candle | null = null;
      let hitMcap = 0;
      for (const c of inWindow) {
        const mcap = (higher ? c.high : c.low) * supply;
        if (higher ? mcap >= bet.targetMcapUsd : mcap <= bet.targetMcapUsd) {
          hit = c;
          hitMcap = mcap;
          break;
        }
      }

      const newestChecked = candles[candles.length - 1].t;
      // A taker win means "never touched", so it needs candles all the way to
      // the deadline — a candle that starts at or after it proves nothing more
      // can land inside the window. The source publishes a minute or two late,
      // which matters for a five-minute bet, so the keeper simply waits for
      // that coverage instead of calling it early.
      const coveredThroughEnd = newestChecked >= bet.expiresAt;

      if (hit) {
        const check = await sanityCheck(
          bet.tokenMint.toBase58(), hit.t, higher, hitMcap, supply,
        );
        if (check.sanity === "deviation") {
          // The two sources disagree about the candle that would decide this.
          // Do not pay anyone on data we cannot corroborate; try again next run.
          const pct = ((check.deviation ?? 0) * 100).toFixed(1);
          await alert("error", "sanity-block",
            `Held back a creator win on ${bet.address}: ${SOURCE} says $${Math.round(hitMcap)}, ` +
            `${SECOND_PROVIDER} says $${Math.round(check.value ?? 0)} (${pct}% apart)`,
            { bet: bet.address, deciding: hitMcap, second: check.value, deviation_pct: pct });
          await mirror(bet, {
            pool_address: pool,
            checked_through: new Date(newestChecked * 1000).toISOString(),
            keeper_note: `sanity check held this back: sources ${pct}% apart`,
          });
          results.push({ bet: bet.address, blocked: "sanity", deviation_pct: pct });
          continue;
        }
        if (check.sanity === "unavailable") {
          await alert("warn", "second-source-down",
            `${SECOND_PROVIDER} had no data for ${bet.tokenMint.toBase58()}; ` +
            `settled ${bet.address} on ${SOURCE} alone`);
        }

        const sig = await send(
          keeper,
          ixSettle(keeper.publicKey, bet, config.feeWallet, OUTCOME_CREATOR_WINS, hitMcap, hit.t),
        );
        await db.from("settlements").upsert({
          bet_address: bet.address,
          outcome: "creator_wins",
          observed_mcap_usd: Math.round(hitMcap),
          observed_at: new Date(hit.t * 1000).toISOString(),
          candle_high_usd: hit.high,
          candle_low_usd: hit.low,
          source: SOURCE,
          pool_address: pool,
          tx_signature: sig,
          deciding_provider: SOURCE,
          deciding_value_usd: Math.round(hitMcap),
          second_provider: SECOND_PROVIDER,
          second_value_usd: check.value === null ? null : Math.round(check.value),
          deviation_pct: check.deviation === null ? null : +(check.deviation * 100).toFixed(3),
          sanity: check.sanity,
        }, { onConflict: "bet_address" });
        await alert("info", "settled",
          `Creator won ${bet.address} at $${Math.round(hitMcap)} (target $${bet.targetMcapUsd})`,
          { outcome: "creator_wins", sanity: check.sanity, sig });
        await mirror({ ...bet, status: "settled", winner: bet.creator }, {
          observed_mcap_usd: Math.round(hitMcap),
          observed_at: new Date(hit.t * 1000).toISOString(),
          pool_address: pool,
          checked_through: new Date(newestChecked * 1000).toISOString(),
        });
        results.push({ bet: bet.address, settled: "creator_wins", mcap: Math.round(hitMcap), sig });
        continue;
      }

      if (now >= bet.expiresAt && coveredThroughEnd) {
        const last = inWindow[inWindow.length - 1] ?? candles[candles.length - 1];
        const lastMcap = last.close * supply;

        // "Never touched" is a claim about the whole window, so the check runs
        // on the point that came closest to the target — if the second source
        // saw that go further, the claim is not safe to act on.
        let peak = last;
        let peakVal = higher ? last.high : last.low;
        for (const c of inWindow) {
          const v = higher ? c.high : c.low;
          if (higher ? v > peakVal : v < peakVal) { peakVal = v; peak = c; }
        }
        const check = await sanityCheck(
          bet.tokenMint.toBase58(), peak.t, higher, peakVal * supply, supply,
        );
        if (check.sanity === "deviation") {
          const pct = ((check.deviation ?? 0) * 100).toFixed(1);
          await alert("error", "sanity-block",
            `Held back a taker win on ${bet.address}: at the window's extreme ${SOURCE} says ` +
            `$${Math.round(peakVal * supply)}, ${SECOND_PROVIDER} says ` +
            `$${Math.round(check.value ?? 0)} (${pct}% apart)`,
            { bet: bet.address, deciding: peakVal * supply, second: check.value, deviation_pct: pct });
          await mirror(bet, {
            pool_address: pool,
            checked_through: new Date(newestChecked * 1000).toISOString(),
            keeper_note: `sanity check held this back: sources ${pct}% apart at the window extreme`,
          });
          results.push({ bet: bet.address, blocked: "sanity", deviation_pct: pct });
          continue;
        }
        if (check.sanity === "unavailable") {
          await alert("warn", "second-source-down",
            `${SECOND_PROVIDER} had no data for ${bet.tokenMint.toBase58()}; ` +
            `settled ${bet.address} on ${SOURCE} alone`);
        }

        const sig = await send(
          keeper,
          ixSettle(
            keeper.publicKey, bet, config.feeWallet,
            OUTCOME_TAKER_WINS, lastMcap, bet.expiresAt,
          ),
        );
        await db.from("settlements").upsert({
          bet_address: bet.address,
          outcome: "taker_wins",
          observed_mcap_usd: Math.round(lastMcap),
          observed_at: new Date(bet.expiresAt * 1000).toISOString(),
          candle_high_usd: last.high,
          candle_low_usd: last.low,
          source: SOURCE,
          pool_address: pool,
          tx_signature: sig,
          deciding_provider: SOURCE,
          deciding_value_usd: Math.round(peakVal * supply),
          second_provider: SECOND_PROVIDER,
          second_value_usd: check.value === null ? null : Math.round(check.value),
          deviation_pct: check.deviation === null ? null : +(check.deviation * 100).toFixed(3),
          sanity: check.sanity,
        }, { onConflict: "bet_address" });
        await alert("info", "settled",
          `Taker won ${bet.address}: never touched $${bet.targetMcapUsd}`,
          { outcome: "taker_wins", sanity: check.sanity, sig });
        await mirror({ ...bet, status: "settled", winner: bet.taker }, {
          observed_mcap_usd: Math.round(lastMcap),
          observed_at: new Date(bet.expiresAt * 1000).toISOString(),
          pool_address: pool,
          checked_through: new Date(newestChecked * 1000).toISOString(),
        });
        results.push({ bet: bet.address, settled: "taker_wins", mcap: Math.round(lastMcap), sig });
        continue;
      }

      // Nothing to do yet — remember how far we got so the next run is cheap.
      const waiting = now >= bet.expiresAt && !coveredThroughEnd;
      await mirror(bet, {
        pool_address: pool,
        checked_through: new Date(newestChecked * 1000).toISOString(),
        keeper_note: waiting
          ? 'past the deadline, waiting for candles to cover the whole window'
          : null,
      });
      results.push({
        bet: bet.address,
        watching: true,
        checked_through: newestChecked,
        waiting_for_coverage: waiting,
      });
    } catch (e) {
      // A bad source or a failed send must never stop the other bets, and the
      // 48h refund remains the safety net.
      await mirror(bet, { keeper_note: String(e).slice(0, 300) });
      results.push({ bet: bet.address, error: String(e).slice(0, 300) });
    }
  }

  if (config.maxOpenExposure && config.openExposure >= config.maxOpenExposure * 0.8) {
    await alert("warn", "exposure-high",
      `Escrow is at ${(config.openExposure / 1e9).toFixed(2)} SOL of a ` +
      `${(config.maxOpenExposure / 1e9).toFixed(2)} SOL cap`);
  }

  return { ok: true, bets: bets.length, matched: matched.length, ms: Date.now() - started, results };
}

/// Constant-time compare, so the token can't be guessed a character at a time.
function sameToken(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

// JWT verification is off because the caller is pg_cron, not a signed-in user.
// Instead the function checks a shared token that Postgres minted into the
// vault and hands over on every request.
Deno.serve(async (req: Request) => {
  const json = (body: unknown, status = 200) =>
    new Response(JSON.stringify(body, null, 2), {
      status,
      headers: { "content-type": "application/json" },
    });
  try {
    const { data: expected } = await db.rpc("keeper_token_get");
    const given = req.headers.get("x-keeper-token") ?? "";
    if (!expected || !sameToken(given, expected as string)) {
      return json({ ok: false, error: "unauthorized" }, 401);
    }
    const action = new URL(req.url).searchParams.get("action");
    if (action === "init-key") return json(await initKey());
    return json(await run());
  } catch (e) {
    return json({ ok: false, error: String(e) }, 500);
  }
});
